import type { INodeProperties } from "n8n-workflow";

import {
  companyIdTypeOptions,
  createLoadOptionsTypeOptions,
  createLookupModeProperty,
  optionalYesNoOptions,
  positiveIntegerTypeOptions,
  positiveNumberTypeOptions,
} from "./propertyOptions";

type DisplayRuleValues = string | string[];
type DisplayRuleMap = Record<string, DisplayRuleValues>;

const show = (
  resource: string,
  operation?: string | string[],
  extraShow: DisplayRuleMap = {},
) => ({
  show: {
    resource: [resource],
    ...(operation
      ? {
          operation: Array.isArray(operation) ? operation : [operation],
        }
      : {}),
    ...Object.fromEntries(
      Object.entries(extraShow).map(([key, value]) => [
        key,
        Array.isArray(value) ? value : [value],
      ]),
    ),
  },
});

function createAppTokenField(
  displayOptions: INodeProperties["displayOptions"],
  description: string,
): INodeProperties {
  return {
    displayName: "App Token",
    name: "appToken",
    type: "string",
    typeOptions: { password: true },
    required: true,
    default: "",
    displayOptions,
    placeholder: "APP_TOKEN",
    description,
  };
}

function createLanguageField(
  displayOptions: INodeProperties["displayOptions"],
  description: string,
): INodeProperties {
  return {
    displayName: "Language",
    name: "langcode",
    type: "options",
    default: "",
    displayOptions,
    description,
    hint: "Loaded from Dots.eco supported languages. Expressions remain available.",
    typeOptions: createLoadOptionsTypeOptions("getSupportedLanguages"),
  };
}

function createCurrencyField(
  displayOptions: INodeProperties["displayOptions"],
  description: string,
): INodeProperties {
  return {
    displayName: "Currency",
    name: "currency",
    type: "options",
    default: "",
    displayOptions,
    description,
    hint: "Loaded from Dots.eco supported currencies. Expressions remain available.",
    typeOptions: createLoadOptionsTypeOptions("getSupportedCurrencies"),
  };
}

const certificateCreateDisplay = show("certificates", "create");
const certificateCreateManualAllocationDisplay = show(
  "certificates",
  "create",
  {
    allocationEntryMode: "manual",
  },
);
const certificateCreateLookupAllocationDisplay = show(
  "certificates",
  "create",
  {
    allocationEntryMode: "lookup",
  },
);
const ecoClubCreateDisplay = show("ecoClub", "createOffering");
const ecoClubCreateManualAllocationsDisplay = show(
  "ecoClub",
  "createOffering",
  {
    limitAllocationsEntryMode: "manual",
  },
);
const ecoClubCreateLookupAllocationsDisplay = show(
  "ecoClub",
  "createOffering",
  {
    limitAllocationsEntryMode: "lookup",
  },
);

const resourceProperty: INodeProperties = {
  displayName: "Resource",
  name: "resource",
  type: "options",
  noDataExpression: true,
  default: "allocations",
  options: [
    { name: "Allocation", value: "allocations" },
    { name: "Application", value: "applications" },
    { name: "Certificate", value: "certificates" },
    { name: "Eco Club", value: "ecoClub" },
    { name: "Flow Card", value: "flowCards" },
    { name: "Impact", value: "impact" },
    { name: "Notification", value: "notifications" },
    { name: "Utility", value: "utility" },
  ],
};

const operationProperties: INodeProperties[] = [
  {
    displayName: "Operation",
    name: "operation",
    type: "options",
    noDataExpression: true,
    default: "list",
    displayOptions: show("allocations"),
    options: [{ name: "List", value: "list", action: "List allocations" }],
  },
  {
    displayName: "Operation",
    name: "operation",
    type: "options",
    noDataExpression: true,
    default: "create",
    displayOptions: show("applications"),
    options: [
      { name: "Create", value: "create", action: "Create application" },
      {
        name: "Get Balance",
        value: "getBalance",
        action: "Get application balance",
      },
    ],
  },
  {
    displayName: "Operation",
    name: "operation",
    type: "options",
    noDataExpression: true,
    default: "create",
    displayOptions: show("certificates"),
    options: [
      { name: "Create", value: "create", action: "Create certificate" },
      {
        name: "Get By App and External ID",
        value: "getByExternalId",
        action: "Get certificate by app and external ID",
      },
      { name: "Get By ID", value: "getById", action: "Get certificate by ID" },
      {
        name: "Get Status",
        value: "getStatus",
        action: "Get certificate status",
      },
      { name: "Get Theme", value: "getTheme", action: "Get certificate theme" },
      {
        name: "List By App and User",
        value: "listByAppAndUser",
        action: "List certificates by app and user",
      },
    ],
  },
  {
    displayName: "Operation",
    name: "operation",
    type: "options",
    noDataExpression: true,
    default: "createOffering",
    displayOptions: show("ecoClub"),
    options: [
      {
        name: "Create Offering",
        value: "createOffering",
        action: "Create eco club offering",
      },
      {
        name: "List Offerings",
        value: "listOfferings",
        action: "List eco club offerings",
      },
    ],
  },
  {
    displayName: "Operation",
    name: "operation",
    type: "options",
    noDataExpression: true,
    default: "create",
    displayOptions: show("flowCards"),
    options: [
      { name: "Create", value: "create", action: "Create flow card" },
      { name: "List", value: "list", action: "List flow cards" },
    ],
  },
  {
    displayName: "Operation",
    name: "operation",
    type: "options",
    noDataExpression: true,
    default: "getSummary",
    displayOptions: show("impact"),
    options: [
      {
        name: "Get Summary",
        value: "getSummary",
        action: "Get impact summary",
      },
      {
        name: "Get Summary Totals",
        value: "getSummaryTotals",
        action: "Get impact summary totals",
      },
    ],
  },
  {
    displayName: "Operation",
    name: "operation",
    type: "options",
    noDataExpression: true,
    default: "createSingleSubscription",
    displayOptions: show("notifications"),
    options: [
      {
        name: "Create Multiple Subscriptions",
        value: "createMultipleSubscriptions",
        action: "Create multiple notification subscriptions",
      },
      {
        name: "Create Single Subscription",
        value: "createSingleSubscription",
        action: "Create single notification subscription",
      },
    ],
  },
  {
    displayName: "Operation",
    name: "operation",
    type: "options",
    noDataExpression: true,
    default: "getSupportedLanguages",
    displayOptions: show("utility"),
    options: [
      {
        name: "Get Supported Currencies",
        value: "getSupportedCurrencies",
        action: "Get supported currencies",
      },
      {
        name: "Get Supported Languages",
        value: "getSupportedLanguages",
        action: "Get supported languages",
      },
    ],
  },
];

const fields: INodeProperties[] = [
  {
    displayName: "Company ID",
    name: "companyId",
    type: "number",
    required: true,
    default: 0,
    displayOptions: show("allocations", "list"),
    typeOptions: companyIdTypeOptions,
    description: "Company ID used to list allocations",
  },
  createLanguageField(
    show("allocations", "list"),
    "Optionally localize allocation labels and descriptions.",
  ),
  {
    displayName: "Name",
    name: "name",
    type: "string",
    required: true,
    default: "",
    displayOptions: show("applications", "create"),
    placeholder: "My App",
    description: "Application name shown in Dots.eco",
  },
  {
    displayName: "Company ID",
    name: "companyId",
    type: "number",
    required: true,
    default: 0,
    displayOptions: show("applications", "create"),
    typeOptions: companyIdTypeOptions,
    description: "Company ID that owns the application",
  },
  {
    displayName: "Share Title",
    name: "shareTitle",
    type: "string",
    required: true,
    default: "",
    displayOptions: show("applications", "create"),
    placeholder: "I just created impact with Dots.eco",
    description: "Default title used when the application is shared",
  },
  {
    displayName: "Share Body",
    name: "shareBody",
    type: "string",
    required: true,
    default: "",
    displayOptions: show("applications", "create"),
    typeOptions: {
      rows: 3,
    },
    placeholder: "Join me in turning everyday actions into measurable impact.",
    description: "Default share message shown for the application",
  },
  {
    displayName: "Logo URL",
    name: "logo",
    type: "string",
    default: "",
    displayOptions: show("applications", "create"),
    placeholder: "https://example.com/logo.png",
    description: "Optional public logo URL for the application",
  },
  {
    displayName: "Social Media Image URL",
    name: "socialMediaImage",
    type: "string",
    default: "",
    displayOptions: show("applications", "create"),
    placeholder: "https://example.com/social-card.png",
    description: "Optional public image URL used for social sharing previews",
  },
  {
    displayName: "Description",
    name: "descriptionText",
    type: "string",
    default: "",
    displayOptions: show("applications", "create"),
    typeOptions: {
      rows: 4,
    },
    placeholder: "Explain what this application does and why it exists.",
    description: "Optional application description shown in Dots.eco",
  },
  {
    displayName: "Download",
    name: "download",
    type: "collection",
    default: {},
    displayOptions: show("applications", "create"),
    options: [
      {
        displayName: "Title",
        name: "title",
        type: "string",
        default: "",
        placeholder: "Download the app",
        description: "Optional label for the download link",
      },
      {
        displayName: "URL",
        name: "url",
        type: "string",
        default: "",
        placeholder: "https://example.com/download",
        description: "Optional public URL for the application download link",
      },
    ],
  },
  {
    displayName: "Share Hashtag",
    name: "shareHashtag",
    type: "string",
    default: "",
    displayOptions: show("applications", "create"),
    placeholder: "#dotsEco",
    description: "Optional hashtag appended to share content",
  },
  createAppTokenField(
    show("applications", "getBalance"),
    "Application token used to fetch the current balance.",
  ),
  createAppTokenField(
    show("certificates", ["create", "listByAppAndUser"]),
    "Application token used to create the certificate or list certificates for a user.",
  ),
  {
    displayName: "External Unique ID",
    name: "externalUniqueId",
    type: "string",
    default: "",
    displayOptions: show("certificates", ["create", "getByExternalId"]),
    placeholder: "order-12345",
    description:
      "External identifier used to deduplicate or retrieve certificates",
    hint: "Must be unique per app when creating a certificate. Reusing the same value returns a 422 from the Dots.eco API.",
  },
  {
    displayName: "Impact Quantity",
    name: "impactQty",
    type: "number",
    required: true,
    default: 1,
    displayOptions: certificateCreateDisplay,
    typeOptions: positiveNumberTypeOptions,
    description: "Amount of impact to attach to the certificate",
  },
  createLookupModeProperty(
    "allocationEntryMode",
    "Allocation Input Mode",
    certificateCreateDisplay,
    "Choose whether to enter the allocation ID manually or select it from Dots.eco.",
  ),
  {
    displayName: "Allocation ID",
    name: "allocationId",
    type: "number",
    required: true,
    default: 0,
    displayOptions: certificateCreateManualAllocationDisplay,
    typeOptions: positiveIntegerTypeOptions,
    description: "Allocation ID to attach to the certificate",
    hint: "Manual mode is preserved for compatibility and expressions.",
  },
  {
    displayName: "Lookup Company ID",
    name: "allocationLookupCompanyId",
    type: "number",
    required: true,
    default: 0,
    displayOptions: certificateCreateLookupAllocationDisplay,
    typeOptions: companyIdTypeOptions,
    description: "Company ID used only to fetch available allocations",
  },
  {
    displayName: "Allocation",
    name: "allocationLookupId",
    type: "options",
    required: true,
    default: "",
    displayOptions: certificateCreateLookupAllocationDisplay,
    typeOptions: createLoadOptionsTypeOptions("getAllocationsForCompany", [
      "allocationLookupCompanyId",
      "langcode",
    ]),
    description: "Select an allocation from Dots.eco to populate Allocation ID",
    hint: "Uses the read token and optional Language selection for localized labels.",
  },
  {
    displayName: "Remote User ID",
    name: "remoteUserId",
    type: "string",
    required: true,
    default: "",
    displayOptions: show("certificates", ["create", "listByAppAndUser"]),
    placeholder: "user-123",
    description: "External user identifier associated with the certificate",
  },
  {
    displayName: "Name on Certificate",
    name: "nameOnCertificate",
    type: "string",
    default: "",
    displayOptions: certificateCreateDisplay,
    placeholder: "Jane Doe",
    description: "Optional name rendered on the certificate",
  },
  {
    displayName: "Remote User Email",
    name: "remoteUserEmail",
    type: "string",
    default: "",
    displayOptions: certificateCreateDisplay,
    placeholder: "jane@example.com",
    description: "Optional email associated with the recipient",
  },
  {
    displayName: "Certificate Design",
    name: "certificateDesign",
    type: "string",
    default: "",
    displayOptions: certificateCreateDisplay,
    placeholder: "default",
    description: "Optional certificate theme or design identifier",
  },
  {
    displayName: "Send Certificate by Email",
    name: "sendCertificateByEmail",
    type: "options",
    default: "",
    displayOptions: certificateCreateDisplay,
    options: optionalYesNoOptions,
    description: "Optionally send the certificate to the recipient by email",
  },
  {
    displayName: "Certificate Info",
    name: "certificateInfo",
    type: "string",
    default: "",
    displayOptions: certificateCreateDisplay,
    placeholder: "Optional custom text or metadata for the certificate.",
    description: "Optional extra information stored with the certificate",
  },
  {
    displayName: "Create Async Image",
    name: "createAsyncImage",
    type: "options",
    default: "",
    displayOptions: certificateCreateDisplay,
    options: optionalYesNoOptions,
    description: "Optionally defer certificate image generation",
  },
  createLanguageField(
    certificateCreateDisplay,
    "Optional language for localized certificate text and claim URLs.",
  ),
  createCurrencyField(
    certificateCreateDisplay,
    "Optional currency for certificate pricing and totals.",
  ),
  {
    displayName: "Certificate ID",
    name: "certificateId",
    type: "string",
    required: true,
    default: "",
    displayOptions: show("certificates", ["getById", "getStatus", "getTheme"]),
    placeholder: "12345",
    description: "Certificate ID returned by Dots.eco",
  },
  {
    displayName: "App ID",
    name: "appId",
    type: "number",
    required: true,
    default: 0,
    displayOptions: show("certificates", "getByExternalId"),
    typeOptions: positiveIntegerTypeOptions,
    description:
      "Numeric application ID used with the external unique ID lookup",
  },
  createAppTokenField(
    show("ecoClub", ["createOffering", "listOfferings"]),
    "Application token used to manage Eco Club offerings.",
  ),
  {
    displayName: "Quantity",
    name: "quantity",
    type: "number",
    required: true,
    default: 1,
    displayOptions: ecoClubCreateDisplay,
    typeOptions: positiveNumberTypeOptions,
    description:
      "Impact quantity to grant when the Eco Club offering is claimed",
  },
  createLookupModeProperty(
    "limitAllocationsEntryMode",
    "Allocation Limit Input Mode",
    ecoClubCreateDisplay,
    "Choose whether to enter allowed allocation IDs manually or select them from Dots.eco.",
  ),
  {
    displayName: "Limit Allocations",
    name: "limitAllocations",
    type: "string",
    default: "",
    displayOptions: ecoClubCreateManualAllocationsDisplay,
    placeholder: "12,34,56",
    description:
      "Optional comma-separated allocation IDs allowed for this offering. Leave empty to allow all allocations.",
    hint: "Manual mode is preserved for compatibility and expressions.",
  },
  {
    displayName: "Lookup Company ID",
    name: "limitAllocationsLookupCompanyId",
    type: "number",
    required: true,
    default: 0,
    displayOptions: ecoClubCreateLookupAllocationsDisplay,
    typeOptions: companyIdTypeOptions,
    description: "Company ID used only to fetch available allocations",
  },
  {
    displayName: "Allocations",
    name: "limitAllocationLookupIds",
    type: "multiOptions",
    required: true,
    default: [],
    displayOptions: ecoClubCreateLookupAllocationsDisplay,
    typeOptions: createLoadOptionsTypeOptions("getAllocationsForCompany", [
      "limitAllocationsLookupCompanyId",
      "langcode",
    ]),
    description: "Select the allocations allowed for this offering",
    hint: "Selected IDs are serialized back into the existing limit_allocations CSV field.",
  },
  {
    displayName: "Name on Certificate",
    name: "nameOnCertificate",
    type: "string",
    default: "",
    displayOptions: ecoClubCreateDisplay,
    placeholder: "Jane Doe",
    description:
      "Optional name rendered on certificates created by this offering",
  },
  {
    displayName: "Activation Date",
    name: "activationDate",
    type: "string",
    default: "",
    displayOptions: ecoClubCreateDisplay,
    placeholder: "YYYY-MM-DD",
    description: "Optional date when the offering becomes active",
  },
  {
    displayName: "Activation Hour",
    name: "activationHour",
    type: "string",
    default: "",
    displayOptions: ecoClubCreateDisplay,
    placeholder: "HH:MM:SS",
    description: "Optional time when the offering becomes active",
  },
  {
    displayName: "Send Email on Activation Date",
    name: "sendEmailOnActivationDate",
    type: "options",
    default: "",
    displayOptions: ecoClubCreateDisplay,
    options: optionalYesNoOptions,
    description:
      "Optionally send the offering email automatically on the activation date",
  },
  {
    displayName: "Code",
    name: "code",
    type: "string",
    default: "",
    displayOptions: ecoClubCreateDisplay,
    placeholder: "EARTHDAY-2026",
    description: "Optional custom claim or redemption code for the offering",
  },
  {
    displayName: "Email",
    name: "mail",
    type: "string",
    default: "",
    displayOptions: ecoClubCreateDisplay,
    placeholder: "jane@example.com",
    description: "Optional email used for the offering recipient or claim flow",
  },
  {
    displayName: "Title",
    name: "title",
    type: "string",
    default: "",
    displayOptions: ecoClubCreateDisplay,
    placeholder: "Claim your impact reward",
    description: "Optional public title for the offering",
  },
  {
    displayName: "Remote User ID",
    name: "remoteUserId",
    type: "string",
    default: "",
    displayOptions: ecoClubCreateDisplay,
    placeholder: "user-123",
    description: "Optional external user identifier associated with the claim",
  },
  {
    displayName: "Max Claims Total",
    name: "maxClaimsTotal",
    type: "string",
    default: "",
    displayOptions: ecoClubCreateDisplay,
    placeholder: "100",
    description: "Optional total number of times the offering can be claimed",
  },
  {
    displayName: "Max Claims Per Email",
    name: "maxClaimsPerEmail",
    type: "string",
    default: "",
    displayOptions: ecoClubCreateDisplay,
    placeholder: "1",
    description: "Optional maximum number of claims allowed per email address",
  },
  createLanguageField(
    ecoClubCreateDisplay,
    "Optional language for localized offering responses and claim URLs.",
  ),
  createCurrencyField(
    ecoClubCreateDisplay,
    "Optional currency for the offering.",
  ),
  {
    displayName: "UUID",
    name: "uuid",
    type: "string",
    default: "",
    displayOptions: show("ecoClub", "listOfferings"),
    placeholder: "4f68d42e-0a83-4d9b-9ef4-98e7f8cb7ff4",
    description: "Optional offering UUID to narrow the list request",
  },
  {
    displayName: "External Unique ID",
    name: "externalUniqueId",
    type: "string",
    default: "",
    displayOptions: show("ecoClub", "listOfferings"),
    placeholder: "campaign-123",
    description: "Optional external unique ID to narrow the list request",
  },
  createAppTokenField(
    show("flowCards", ["create", "list"]),
    "Application token used to create or list flow cards.",
  ),
  {
    displayName: "SKU",
    name: "sku",
    type: "string",
    required: true,
    default: "",
    displayOptions: show("flowCards", "create"),
    placeholder: "FLOW-CARD-SKU",
    description: "SKU of the flow card to create",
  },
  {
    displayName: "Expiration Date",
    name: "expirationDate",
    type: "string",
    default: "",
    displayOptions: show("flowCards", "create"),
    placeholder: "YYYY-MM-DD",
    description: "Optional expiration date for the flow card",
  },
  {
    displayName: "Recipient Email",
    name: "recipientEmail",
    type: "string",
    default: "",
    displayOptions: show("flowCards", "create"),
    placeholder: "jane@example.com",
    description: "Optional recipient email address",
  },
  {
    displayName: "Recipient Name",
    name: "recipientName",
    type: "string",
    default: "",
    displayOptions: show("flowCards", "create"),
    placeholder: "Jane Doe",
    description: "Optional recipient name shown on the flow card",
  },
  {
    displayName: "Sender Name",
    name: "from",
    type: "string",
    default: "",
    displayOptions: show("flowCards", "create"),
    placeholder: "Dots.eco",
    description: "Optional sender name shown on the flow card",
  },
  {
    displayName: "Message",
    name: "message",
    type: "string",
    default: "",
    displayOptions: show("flowCards", "create"),
    typeOptions: {
      rows: 4,
    },
    placeholder: "Thanks for helping make an impact.",
    description: "Optional message included with the flow card",
  },
  {
    displayName: "Company ID",
    name: "companyId",
    type: "string",
    default: "",
    displayOptions: show("impact", ["getSummary", "getSummaryTotals"]),
    placeholder: "12345",
    description: "Optional company ID used to scope the summary",
    hint: "At least one of Company ID or App Tokens is required.",
  },
  {
    displayName: "App Tokens",
    name: "appTokens",
    type: "string",
    typeOptions: { password: true },
    default: "",
    displayOptions: show("impact", ["getSummary", "getSummaryTotals"]),
    placeholder: "APP_TOKEN_ONE,APP_TOKEN_TWO",
    description:
      "Optional comma-separated app tokens used to scope the summary",
    hint: "At least one of Company ID or App Tokens is required.",
  },
  {
    displayName: "Remote User ID",
    name: "remoteUserId",
    type: "string",
    default: "",
    displayOptions: show("impact", ["getSummary", "getSummaryTotals"]),
    placeholder: "user-123",
    description: "Optional external user identifier used to narrow the summary",
  },
  {
    displayName: "Certificate ID",
    name: "certificateId",
    type: "string",
    required: true,
    default: "",
    displayOptions: show("notifications", [
      "createSingleSubscription",
      "createMultipleSubscriptions",
    ]),
    placeholder: "12345",
    description:
      "Certificate ID whose notification subscriptions should be created",
  },
  {
    displayName: "Name",
    name: "name",
    type: "string",
    default: "",
    displayOptions: show("notifications", "createSingleSubscription"),
    placeholder: "Jane Doe",
    description: "Optional subscriber name. Either Name or Email is required.",
  },
  {
    displayName: "Email",
    name: "email",
    type: "string",
    default: "",
    displayOptions: show("notifications", "createSingleSubscription"),
    placeholder: "jane@example.com",
    description: "Optional subscriber email. Either Name or Email is required.",
  },
  {
    displayName: "Data Processing Consent",
    name: "dataProcessingConsent",
    type: "boolean",
    default: false,
    displayOptions: show("notifications", "createSingleSubscription"),
    description: "Whether the subscriber has provided data-processing consent",
  },
  {
    displayName: "Subscriptions",
    name: "subscriptions",
    type: "fixedCollection",
    required: true,
    default: {},
    displayOptions: show("notifications", "createMultipleSubscriptions"),
    typeOptions: {
      multipleValues: true,
    },
    options: [
      {
        name: "subscription",
        displayName: "Subscription",
        values: [
          {
            displayName: "Name",
            name: "name",
            type: "string",
            default: "",
            placeholder: "Jane Doe",
            description: "Optional subscriber name",
          },
          {
            displayName: "Email",
            name: "email",
            type: "string",
            default: "",
            placeholder: "jane@example.com",
            description: "Optional subscriber email",
          },
          {
            displayName: "Data Processing Consent",
            name: "dataProcessingConsent",
            type: "boolean",
            default: false,
            description:
              "Whether the subscriber has provided data-processing consent",
          },
        ],
      },
    ],
    description: "One or more notification subscriptions to create",
  },
];

export const dotsEcoNodeProperties: INodeProperties[] = [
  resourceProperty,
  ...operationProperties,
  ...fields,
];
